/*
 * led_7_seg.c
 *
 *  Created on: Nov 4, 2022
 *      Author: NHAN
 */


#include "led_7_seg.h"

void display_led_7seg(int number){
	switch(number){
	case 0:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_SET);
		break;
	case 1:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_SET);
		break;
	case 2:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 4:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 5:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 6:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 7:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_SET);
		break;
	case 8:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	case 9:
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, LED_7SEG_G_Pin, GPIO_PIN_RESET);
		break;
	default:
		break;
	}
}


